### PR TITLE
Ch coveralls integration #162633494

### PR DESCRIPTION
**Pull request by NabunyaLilian**
#### What does this PR do?
 Adds Coveralls integration to attain code coverage service

#### Description of Task to be completed?
* Add a .coveralls.yml file
* Install coverage and coveralls

#### How should this be manually tested?
After Travis is done passing, code coverage will automatically connect with it.

#### What are the relevant pivotal tracker stories ?
[#162633494](https://www.pivotaltracker.com/n/projects/2231917/stories/162633494)

### CODE REVIEW

**Comment by lym** [comment]
@NabunyaLilian Please have the coveralls badge on its own line. The README is less cluttered that way.

**Comment by lym** [comment]
LGTM

**Comment by araaliFarooq** [comment]
Looks Good To Me

**Comment by jeanjoe** [comment]
LGTM

**Comment by mubstimor** [comment]
LGTM

**Comment by mycok** [comment]
LGTM

**Comment by fatukunda** [comment]
LGTM

**Pull request merged**
