### PR TITLE
Ft social auth login #162633500

### PR DESCRIPTION
**Pull request by araaliFarooq**
### What does this PR do?

* Implements user login via facebook and google

#### Description of tasks to be implemented

* Add social login capabilities to enable users login into the application using their social media accounts
* Write test cases for the module

##### Endpoints to be tested
* POST /api/v1/auth/facebook/
* POST /api/v1/auth/google/

Using postman, test the above endpoints using the following request headers
Content-Type: application/json
Authorization: None
Body : {"user":{ "auth_token": "EAAEBLo2bPF0BAGYZCZBZAZCjZAcykZCrb67JiJZAerTyigY9Rmsa........."}}

#### Running tests
* python manage.py test authors/apps/authentication/tests/test_social_auth.py

#### What are the relevant PT stories?
* Delivers #162633500

### CODE REVIEW

**Comment by mycok** [comment]
Sorry can't review a failing build. Try to figure out why your build is failing then i can review your PR.

**Comment by mycok** [comment]
LGTM

**Comment by mubstimor** [comment]
LGTM

**Comment by jeanjoe** [comment]
LGTM

**Comment by fatukunda** [comment]
LGTM

**Pull request closed without merging**
