### PR TITLE
162633501: Feature(User profile)  Create User Profile Module

### PR DESCRIPTION
**Pull request by fatukunda**
**What does this PR do?**

- Creates a user profile module

**Description of the tasks to be completed**

- Create models, serializers, views, and renderers of the profile app

- Create a signals.py file to ensure that everytime a user is created, then a corresponding profile is also created

- Create a custom authentication AppConfig file to run the created signal

- Modify the authentication serializers, and views to add profile information for each user

- Create a tests folder and write tests for the profiles module

**How should this be manually tested?**

- Pre-requisites
       - `export DATABASE_URL=postgres://user:password@localhost:5432/database `in your python 
       environment.
       - `export SECRET_KEY='this-is-hard-to-break'`
       - `python manage.py test authors/apps/profiles/tests`

- Endpoints to be tested
     - `GET /api/v1/users/<pk>/profile`
     - `PUT / api/v1/users/<id>`

**What are the relevant PT stories?**

- [Delivers #162633501](https://www.pivotaltracker.com/story/show/162633501)

### CODE REVIEW

**Comment by jeanjoe** [comment]
Please add all the steps to get the app running in the description

**Comment by jeanjoe** [comment]
LGTM

**Comment by NabunyaLilian** [comment]
Nice work Frank, though could you add holder text the database URL instead.

**Comment by NabunyaLilian** [comment]
LGTM

**Comment by mubstimor** [comment]
My only suggestion would be to enable accessing profile information using a username for example GET /api/profiles/:username since ids maybe trickier to use. otherwise LGTM

**Pull request merged**
