### PR TITLE
#162633509 Ft list users functionality 

### PR DESCRIPTION
**Pull request by NabunyaLilian**
**What does this PR do?**

Enables list users functionality to only authenticated users. 

**Description of Tasks completed**

* Add a view for listing users
* Add a route for the view
* Test the view and refactor until it passes.

**How to manually test**
- `export DATABASE_URL=postgres://<username>:<password>@localhost:5432/<db-name> `in your python 
       environment.
- `python manage.py makemigrations`
- `python manage.py migrate`
- `export SECRET_KEY='this-is-hard-to-break'`
- `python manage.py test`
* Register and login a user
- ` http://127.0.0.1:8000/api/v1/users/register`
-  `http://127.0.0.1:8000/api/v1/users/login/`
- `http://127.0.0.1:8000/api/v1/users/`

**Relevant pivotal tracker story**

[DELIVERS #162633509](https://www.pivotaltracker.com/story/show/162633509)

### CODE REVIEW

**Comment by mubstimor** [comment]
LVGTM

**Comment by Qadriyah** [comment]
LGTM

**Comment by mycok** [comment]
LGTM

**Comment by fatukunda** [comment]
LGTM

**Comment by jeanjoe** [comment]
LGTM

**Pull request merged**
