### PR TITLE
#162633508-ft-(user-notifications): Users should recieve email notifications  …

### PR DESCRIPTION
**Pull request by mycok**
#### What does this PR do?

Implements functionality that enables users to receive email notifications when specific events are triggered such as an article author posting new content/ new article or when a user follows another user.

#### Description of Tasks completed

* Added a notify app package
* Added a mail list model to store user notification subscriptions.
* Added serializers for mail list models
* Added notify urls for both mail list model and the notifications model
* Added notify urls to the project root urls
* Added tests for user notifications

#### How to manually test the above functionality.
* pip install -r requirements.txt to add django-notifications-hq package
* Register and login a user
* create and post an article:  Incase you wish to test notifications for posting an article
* Use the user profile object to add a follower/ follow another user: Incase you wish to test notifications for following another user
* Register and login another user: Since you can't follow yourself, you need to create another user to follow you in order to trigger an event that will in turn trigger a notification to your email account.

##### Mail List 
`GET /api/v1/mail_list : Fetch all mail list subscribed users`
`GET /api/v1/mail_list_subscribe : Subscribe for notifications`
`PUT /api/v1/mail_list_subscribe : Opt-in or Opt-out of notifications`

##### Notifications
`GET /api/v1/notifications/ : Fetch all notifications for a logged in user`
`GET /api/v1/notifications/unread : Fetch all unread notifications for a logged in user`
`GET /api/v1/notifications/read : Fetch all read notifications for a logged in user`
`GET /api/v1/notifications/mark-as-read : Mark all user notifications as read`

[DELIVERS #162633508]
(https://www.pivotaltracker.com/story/show/162633508)

### CODE REVIEW

**Comment by araaliFarooq** [comment]
LGTM

**Comment by fatukunda** [comment]
LGTM

**Comment by jeanjoe** [comment]
LGTM

**Comment by araaliFarooq** [comment]
LGTM

**Comment by Qadriyah** [comment]
LGTM

**Comment by jeanjoe** [comment]
Please resolve your conflicts so that your work can be merged.

**Pull request merged**
